### ISSUE TITLE
El uso de `header` con un parámetro desconocido en dev genera un 500

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#115]
http://181.209.63.223:8095/series/?ids=143.3_NO_PR_2004_A_21&header=description&format=csv

Estaba intentando probar el PR que acabo de ver mergeado (consciente de que probablemente todavía no estuviera deployado en dev) y esperaba (a) que mágicamente funcione o (b) que me arroje un error "controlado" pero levantó un 500.

Habría que revisar que todos los argumentos de la API que existen validen el input entre las posibilidades que están implementadas, y arrojen un error controlado más que un 500.

De todas maneras, si esto no causó un problema en el servidor, sería de baja prioridad hasta haber podido completar los otros issues.

**Comment by lucaslavandeira** [comment]
Este bug fue encontrado y corregido con el PR del issue #87, y en efecto, falta hacer el deploy
