### ISSUE TITLE
Implementar capacidad de seleccionar los datasets que se federan de cada nodo

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#134]
**Contexto**

Hoy todos los datasets que contienen series de tiempo en alguno de los nodos monitoreados se incorporan automáticamente a la base.

La política de apertura de datos.gob.ar no federa nuevos datasets automáticamente, sin pasar antes por un control de calidad manual.

Debe implementarse un mecanismo para seleccionar los datasets (de entre aquellos que tienen series de tiempo) que se van a indexar en la base y los que no, en el admin de Django.

**Propuesta**

Implementar una _whitelist_ de datasets a indexar con una interfaz visual manual y otra _bulk_ (mediante la carga de un archivo) que permite a un operador administrador de la base elegir qué datasets deben ser indexados.

*Interfaz visual*

- [x] Debe permitir ver una lista de los datasets que en la última corrida fueron identificados como "tienen series de tiempo", para cada uno de los nodos analizados.
- [x] Debe permitir seleccionar / des-seleccionar un dataset para su indexación
- [x] Debe permitir borrar uno o todos los datasets de la lista de un nodo.

*Interfaz bulk*

- [x] Debe aceptar y validar la carga manual de un archivo CSV, con la especificación que se ve en el ejemplo adjunto, donde **sólo se usan los campos `catalog_id` y `dataset_identifier`) para agregar nuevos datasets a la indexación. La implementación no debe confiar en el orden de los campos del CSV, sino en su nombre.
- [x] Cada uno de los datasets (identificados por la combinación del id del nodo y del id del dataset) que figure en uno de esos archivos cargados manualmente por el administrador debe agregarse a la lista de datasets de cada nodo _seleccionado para su federación_

**Notas**

- No hay forma de "des-seleccionar" datasets para su federación con la interfaz bulk (con esa modalidad sólo se pueden cargar seleccionados nuevos datasets).
- Un dataset nuevo que se encuentra en un nodo, se agrega a la lista **des-seleccionado** por default. Debe haber una acción explícita para indexar un nuevo dataset.
- La lista de datasets que se puede seleccionar o des-seleccionar, se actualiza con cada corrida de indexación.
- Si un dataset que estaba en la lista ya no está en la próxima corrida de indexación, este *no se borra de la lista*. Debe aparecer alguna indicación (verde / roja) de que el dataset que se ve en la lista no fue encontrado en la última indexación o sí fue encontrado.
- La identificación unívoca de un dataset debe descansar siempre en el uso combinado del id del nodo (`catalog_id`) y del id del dataset (`dataset_identifier`).

**Modelo de archivo CSV para carga bulk**

Aparentemente Github _no soporta la carga de CSVs en issues!_ así que [va un link](https://www.dropbox.com/s/mcu37qlhh0yqbm0/federacion-config-sspm-2018-01-02.csv?dl=0)

**Comment by poligarcia** [comment]
@lucaslavandeira acordate de ir tildando los checks a medida que vas implementando los features!
