### ISSUE TITLE
Continuous delivery para staging

### ISSUE THREAD

**Issue by poligarcia** [datosgobar/series-tiempo-ar-api#137]
Continuar con la implementación de continuous delivery implementada para el ambiente de desarrollo, pero para el ambiente de staging.

El deploy debe dispararse automáticamente al realizarse un nuevo tag en el repositorio.

**Comment by poligarcia** [comment]
@lalo73 podrás agregar algún step al deploy para que *sólo en staging* desencripte un perfil de openvpn y se conecte?

Seguramente hay que asegurarse de que se desconecte cuando termine...

**Comment by abenassi** [comment]
perdón! Creé el issue #178 porque no había visto que estaba este en el backlog antes

**Comment by lalo73** [comment]
Para próximas implementaciones, verificar: https://github.com/travis-ci/travis.rb/issues/239
