### ISSUE TITLE
Revisar exportación de analytics

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#141]
- [x] Hoy se muestran 11k de consultas cuando parecen ser casi 20k. 
- [x] Poder filtrar por fecha
- [ ] Sumar más columnas de información sin perjudicar la performance (pasan el JSON para revisar cuáles son los campos útiles)

**Comment by poligarcia** [comment]
Bastante tarde, pero aquí va una muestra de lo que el plugin nos provee, como para agregar info adicional al logging: https://getkong.org/plugins/http-log/#log-format

**Comment by poligarcia** [comment]
@abenassi acá tenés una config de swagger para TS en estado WIP: https://gist.github.com/poligarcia/17cf348fa898950998a5379beb899e6f

Me falta modelar la respuesta!

**Comment by abenassi** [comment]
Buenísimo @poligarcia !

2018-01-25 12:46 GMT-03:00 Poli García <notifications@github.com>:

**Comment by poligarcia** [comment]
Pero le pifié MAL al issue!

Ahora lo pongo en el issue que corresponde

**Comment by abenassi** [comment]
Se hace lo que se puede :-)

2018-01-25 12:53 GMT-03:00 Poli García <notifications@github.com>:

**Comment by poligarcia** [comment]
El punto 
> Sumar más columnas de información sin perjudicar la performance (pasan el JSON para revisar cuáles son los campos útiles)
Lo vamos a administrar desde datosgobar/api-gateway#19

El punto
>Hoy se muestran 11k de consultas cuando parecen ser casi 20k.
ya fue resuelto
