### ISSUE TITLE
Realizar consultas de series largas

### ISSUE THREAD

**Issue by santosbs** [datosgobar/series-tiempo-ar-api#144]
Buenas, felicitaciones por la herramienta. No soy programador pero una vez que le agarras la mano es facil de usar. El unico problema que estoy encontrando es que las consultas me devuelven por default 100 datos nomas y no encuentro donde poder modificarlo. gracias

**Comment by lucaslavandeira** [comment]
Hola @santosbs! Se pueden realizar consultas de más datos agregando el parámetro `limit` a la consulta. Acepta valores hasta 1000. Te dejo un ejemplo: 
http://apis.datos.gob.ar/series/api/series/?ids=135.1_M_0_0_6&limit=1000

**Comment by santosbs** [comment]
Muchas gracias, 1000 es por el momento el limite maximo? Trabajo con series
diarias (Tipo de cambio) de larga data.

gracias nuevamente

santos

2018-01-11 11:30 GMT-03:00 Lucas Lavandeira <notifications@github.com>:

**Comment by lucaslavandeira** [comment]
Sí, actualmente el máximo está fijado en 1000. 

Saludos
