### ISSUE TITLE
Implementar documentación básica en Swagger / OpenAPI

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#150]
**Contexto**

Próximamente las APIs de datos.gob.ar se van a publicar en una landing integrada (apis.datos.gob.ar) que liste y apunte a la documentación de cada una de las APIs, que viviría es sus endpoints respectivos (apis.datos.gob.ar/series , apis.datos.gob.ar/georef , etc) antes del /api/.

Junto con esta implementación, se buscaría sugerir como buena práctica para la documentación y apertura de APIs de datos algún estándar de documentación de APIs y requerimientos mínimos de elementos que una API debe cumplir y documentar para estar abierta.

Durante 2018, se apuntaría a desarrollar estas buenas prácticas de documentación de APIs utilizando las de datos.gob.ar como casos testigo, para finalizar el año pudiendo dar una recomendación general para la apertura de servicios en la APN.

**Propuesta**

El estándar más utilizado parece ser Swagger / Open API. Para poder explorarlo con un ejemplo, implementaremos una primer versión básica de documentación en este estándar para la API de series de tiempo:

- Usando Github Pages, en este mismo repositorio.
- Replicando exclusivamente la documentación de los parámetros del único endpoint de la API (que están en https://series-tiempo-ar-api.readthedocs.io/es/latest/api_reference/ )
- Agregando nuevas recetas al Makefile para levantar localmente la documentación del estándar (`make servedocs-openapi)` y generar un build en el repositorio para que se publique en github pages (`make docs-openapi`). En forma similar a como está hecho para la documentación en RTD.

**Notas**

Durante la implementación tener en cuenta:

- Facilidad de edición de la documentación (si es que hay más de una opción a elegir).
- Pros y contras de que la documentación sea sin tocar código alguno de la API o tocándolo (bajo el pre-supuesto de que es más difícil implementar este estándar si implica tocar código de una API).

**Comment by poligarcia** [comment]
@abenassi acá tenés una config de swagger para TS en estado WIP: https://gist.github.com/poligarcia/17cf348fa898950998a5379beb899e6f

Podés pegar el contenido en editor.swagger.io y ver cómo se comporta.

Me falta modelar la respuesta!

**Comment by abenassi** [comment]
Ahora sí!

2018-01-25 12:53 GMT-03:00 Poli García <notifications@github.com>:

**Comment by abenassi** [comment]
@poligarcia tengo de hace tiempo el editor online de swagger abierto para ir probando *cómo metería las otras secciones de documentación* que hay en series-tiempo-ar-api.readthedocs.io que no son la parte de la "tabla de parámetros y sus respuestas" pero todavía no le encuentro la vuelta a cómo manejar un _seccionado_ de la misma manera (o similar) a la que se hace en RTD.

Sin embargo, el Jueves vamos a hablar con gente de un nodo que tiene una API que documentar y nos gustaría mostrarle un ejemplo funcionando de Open API docs (este ejemplo) implementados sobre un repo con el `Makefile` para buildear los docs y que se vean en el Github Pages del repo. Así los impulsamos a usar el mismo estándar.

Podremos mover el gist yaml este a la carpeta `docs` (https://github.com/datosgobar/series-tiempo-ar-api/tree/master/docs)  y agregar las recetas al `Makefile` que sean necesarias para buildearla?? Yo ya apunté Github Pages a la carpeta `docs`(https://datosgobar.github.io/series-tiempo-ar-api/) pero en realidad tendría que encontrar ahí un *index.html* que sean los docs de Open API buildeados.

**Comment by poligarcia** [comment]
@abenassi sería algo así? https://poligarcia.github.io/test-docs/swagger/

Fijate como quedó 97f52d3124b9243cf592432a16b64cc32c045ab6 en el branch [`150-documentacion-swagger`](/datosgobar/series-tiempo-ar-api/tree/150-documentacion-swagger)
