### ISSUE TITLE
Reporte de indexación de la API [Errores]

### ISSUE THREAD

**Issue by lalo73** [datosgobar/series-tiempo-ar-api#151]
Despues de la implementación de #128, ver de registrar los Jobs fallidos, de manera que pueda verse por qué fallaron.

**Comment by poligarcia** [comment]
Esta tarea debería estar en este proyecto? https://github.com/orgs/datosgobar/projects/10

**Comment by poligarcia** [comment]
Vamos a trackear este issue en el #152
