### ISSUE TITLE
Resultado de indexación de la API [Reporte]

### ISSUE THREAD

**Issue by lalo73** [datosgobar/series-tiempo-ar-api#152]
Después de la implementación de #128.

Mejorar cómo se guardan los reportes.
La implementación actual hace uso de un JSON, ver de guardarlo en un modelo de Django.
Quizás es mejor hacerlo después de la #151

**Comment by poligarcia** [comment]
Esta tarea debería estar en este proyecto? https://github.com/orgs/datosgobar/projects/10

**Comment by poligarcia** [comment]
Durante el Sprint 6 vamos a persistir las métricas calculadas para enviar en el reporte en algún modelo de la aplicación.
