### ISSUE TITLE
API de búsqueda de Field

### ISSUE THREAD

**Issue by lalo73** [datosgobar/series-tiempo-ar-api#169]
Agregar un endpoint en `/api/search/` que busque sobre series de tiempo, entidades "field".

Las mismas tiene un aspecto:
```
{
    title: string,
    type: string,
    description: string,
    id: string,
    units: string,
    specialType: string,
    specialTypeDetails: string,
}
```

Las entidades deben ser indexadas en lo posible usando [elasticsearch-dsl](http://elasticsearch-dsl.readthedocs.io/en/latest/index.html), usando modelos.

Debe poder agregarse un comando `python manage.py index_metadata [datajson_url]` que corra la indexacion de estos modelos.

Como primer versión, el único parámetro a implementar en este endpoint es `q`.
El mismo debe buscar en los campos `id`, `title` y `description`.

La busqueda debe implementarse con la lógica de [Query context](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-filter-context.html#query-filter-context), mediante la libreria.

La respuesta esperada es:

```json
{
    "limit": 20,
    "offset": 0,
    "count": 1,
    "data": [
        {
            "title": "foo",
            "description": "bar",
            "id": "if-foo",
       }
    ] 
}
```

**Comment by lucaslavandeira** [comment]
>Las entidades deben ser indexadas en lo posible usando elasticsearch-dsl, usando modelos.

`elasticsearch-dsl` no ofrece indexación en bulk, es necesario usar `elasticsearch` que lee diccionarios con los mappings de documentos. Se podría implementar los doctypes en `elasticsearch-dsl` y luego hacer un `.to_dict()` para convertirlos, pero es más facil armar el dict directamente sin pasar por el DSL

**Comment by lalo73** [comment]
Yo preferiría quedarme en `elasticsearch-dsl` y usando lo mencionado aca en el issue 403 de `elastic/elasticsearch-dsl-py`.
Lo dejo a tu criterio.
