### ISSUE TITLE
API de búsqueda de units de Field

### ISSUE THREAD

**Issue by lalo73** [datosgobar/series-tiempo-ar-api#174]
Agregar un endpoint en `/api/search/field_units` que busque los "units" de los fields, clave opcional "units".

Las mismas hoy por hoy son strings.

Puede haber dos implementaciones:

1)

Las entidades deben ser indexadas en lo posible usando [elasticsearch-dsl](http://elasticsearch-dsl.readthedocs.io/en/latest/index.html), usando modelos.

Debe poder agregarse un comando `python manage.py index_metadata [datajson_url]` que corra la indexacion de estos modelos. Teniendo una opcion `--units` para sólo indexar estos valores.

2)

Haciendo una busqueda sobre los valores únicos e indexando los datasets.
Usando [terms](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html). Un ejemplo de [Stackoverflow](https://stackoverflow.com/questions/25465215/elasticsearch-return-unique-values)

La respuesta esperada es:

```json
[
        "Millones en pesos a precio de 1993"
] 
```

**Comment by abenassi** [comment]
Se testeó con http://apis-stg.datos.gob.ar/series/api/search/field_units y aparece la lista vacía (tendría que haber varios).

**Comment by lucaslavandeira** [comment]
Eso probablemente se deba a que no se corrió la indexación de metadatos
desde que se deployó este endpoint, que aún no está automatizada. Si es el
caso, prueben corriendo el comando `index_metadata` nuevamente y reintentar
una vez que haya terminado!
