### ISSUE TITLE
API de búsqueda de "publisher_name" de dataset

### ISSUE THREAD

**Issue by lalo73** [datosgobar/series-tiempo-ar-api#175]
Agregar un endpoint en `/api/search/dataset_publisher_name` que busque los "publisher.name" de los datasets.

Las mismas hoy por hoy son strings.

Puede haber dos implementaciones:

1)

Las entidades deben ser indexadas en lo posible usando [elasticsearch-dsl](http://elasticsearch-dsl.readthedocs.io/en/latest/index.html), usando modelos.

Debe poder agregarse un comando `python manage.py index_metadata [datajson_url]` que corra la indexacion de estos modelos. Teniendo una opcion `--publisher-name` para sólo indexar estos valores.

2)

Haciendo una busqueda sobre los valores únicos e indexando los datasets.
Usando [terms](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html). Un ejemplo de [Stackoverflow](https://stackoverflow.com/questions/25465215/elasticsearch-return-unique-values)

La respuesta esperada es:

```json
[
        "Ministerio de modernizacion",
        "Oficina NAcional de Contrataciones",
] 
```

**Comment by abenassi** [comment]
Se testeó este endpoint con http://apis-stg.datos.gob.ar/series/api/search/dataset_publisher_name y la lista está vacía. Debería haber por lo menos un valor, ya que todos los datasets que hay en staging tienen un "dataset_publisher_name".

**Comment by abenassi** [comment]
@poligarcia @lucaslavandeira yo había movido esto a "To Do" porque hoy no anduvo, hay que revisar que funcione correctamente. Lo trackean de alguna otra manera??

**Comment by lucaslavandeira** [comment]
Beni recién hace una hora detecté el problema que había, y lo corregí y
cerré el issue. Para el deploy de la semana que viene se verá reflejado el
cambio en stg para que lo revises

**Comment by abenassi** [comment]
Oka, buenísimo

2018-03-28 16:45 GMT-03:00 Lucas Lavandeira <notifications@github.com>:
