### ISSUE TITLE
API de búsqueda de Field extendida

### ISSUE THREAD

**Issue by lalo73** [datosgobar/series-tiempo-ar-api#176]
Después de implementar #169, extender el rango de búsqueda del parametro `q`.

El parámetro `q` debe buscar en los campos `id`, `title`, `description`, `theme_description`, `dataset_source`, `dataset_description` y `dataset_title`.
Estos valores deben tomarse de:

- 'theme_description': `description` del tema de su dataset.
- 'dataset_source': `source` de su dataset
- 'dataset_description': `description` de su dataset
- 'dataset_title': `title` de su dataset

La respuesta esperada es:

```json
{
    "limit": 20,
    "offset": 0,
    "count": 1,
    "data": [
        {
            "title": "foo",
            "description": "bar",
            "id": "if-foo"
       }
    ] 
}
```

**Comment by abenassi** [comment]
@poligarcia @lalo73 no hay valor en partir esta implementación en dos iteraciones distintas??

Primera iteración: `q` hace una búsqueda "simple" dentro de id, title y description (todos metadatos *primarios* y que pertenecen a field).

Segunda iteración: `q` expande su búsqueda a los metadatos *secundarios*, e incorpora ponderaciones para diferenciarlos en importancia de los primarios.

Tal vez el esfuerzo de implementar sólo 1 es casi el mismo de implementar 2, y prefieren hacerlo todo junto... pero si no es así, la parte 2 me parece mejor iterarla y no abordarla en este sprint.

**Comment by abenassi** [comment]
Esto ya está implementado.
