### ISSUE TITLE
Ejecutar prueba de consistencia de analytics para TS

### ISSUE THREAD

**Issue by poligarcia** [datosgobar/series-tiempo-ar-api#184]
Armar y ejecutar una prueba de consistencia de analytics para la API de Series de Tiempo, contra el ambiente de staging.

La idea sería pegarle al endpoint de series, 100 veces para cada una de las series indexadas (unas 14K) y verificar que se loguean 100 llamadas por cada serie en el analytics.

cc @llavandeira

**Comment by lucaslavandeira** [comment]
Se ejecutó una iteración de 100 veces de varias (no todas) las series, y otra de 20 clientes ejecutando 200 requests cada una. En ambos casos todas las Queries hechas se loguearon al panel de admin correctamente
