### ISSUE TITLE
Investigar error en la exportación de analytics en producción

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#188]
La exportación de analytics en la instancia productiva dio un error de Kong.

<img width="512" alt="screenshot 2018-02-09 18 35 21" src="https://user-images.githubusercontent.com/4405346/36051274-489404be-0dc8-11e8-9b87-472d6587148a.png">

En la instancia de staging también

<img width="538" alt="screenshot 2018-02-09 18 41 07" src="https://user-images.githubusercontent.com/4405346/36051431-db6015c6-0dc8-11e8-9378-f2479b806801.png">

**Comment by lucaslavandeira** [comment]
Corregido desde el lado del deploy
