### ISSUE TITLE
Reporte de indexación: Nuevos campos

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#197]
**Contexto**

Al reporte de indexación tal como está ahora le faltan varios campos para:

+ Entender mejor el resultado de la corrida (monitoreo API)
+ Seguir la evolución del universo de series disponible en la red de nodos (monitoreo nodos)

**Propuesta**

Modificar el reporte según el modelo de abajo. Aclaro en cada caso el significado esperado/interpretado del usuario ante cada campo.

`Catálogos`:
    **nuevos**: _son los catálogos que el admin agregó como "indexable" de la lista de "Nodes" y todavía no habían sido indexados nunca por primera vez_
    **actualizados**: _son los catálogos que tuvieron por lo menos alguna modificación de datos o metadatos en la corrida de indexación, si no hubo *ningún cambio en datos ni en metadatos, no debería considerarse actualizado_
    **no actualizados**: _son los catálogos que no tuvieron **ningún cambio en datos ni en metadatos en esta corrida**_
    **totales**: _son los catálogos que están en la lista de indexación de la API, los que va a recorrer en busca de cambios en los metadatos o de cambios en los datos_

`Datasets`:
**nuevos**: _son los datasets con series de tiempo que la API encontró en los catálogos en esta corrida, que no había visto antes. Son los que se agregan a la lista de datasets con default "no indexable" por primera vez. Permiten al usuario saber que hay nuevos datasets con series de tiempo para su consideración_
**no indexables**: _la cantidad de datasets marcados como "no indexables", incluyendo los nuevos incorporados en esta corrida_
**indexables**: _la cantidad de datasets marcados como "indexables"_
**actualizados**:  _son los datasets **indexables** que tuvieron por lo menos alguna modificación de datos o metadatos en la corrida de indexación, si no hubo *ningún cambio en datos ni en metadatos de un dataset, no debería considerarse actualizado_
**no actualizados**:   _son los datasets **indexables** que no tuvieron **ningún cambio en datos ni en metadatos en esta corrida**_
**error**:  _son los datasets cuya actualización se intentó pero arrojaron error parcial o total en el intento de actualización_
**totales**: _es el total de datasets con series de tiempo que hay en los catálogos indexables al día de hoy (datasets indexables + datasets no indexables)

`Distribuciones`:
**nuevos**: _son las distribuciones con series de tiempo que la API encontró en datasets nuevos en esta corrida, que no había visto antes. Son los pertenecientes a los datasets que se agregan a la lista de datasets con default "no indexable" por primera vez. Permiten al usuario saber cuántas nuevas distribuciones con series de tiempo hay para su consideración_
**no indexables**: _la cantidad de distribuciones con series de tiempo que hay en datasets marcados como "no indexables", incluyendo los nuevos incorporados en esta corrida_
**indexables**: _la cantidad de distribuciones con series de tiempo que hay en datasets marcados como "indexables"_
**actualizados**:  _la cantidad de distribuciones con series de tiempo que hay en datasets **indexables** que tuvieron por lo menos alguna modificación de datos o metadatos en la corrida de indexación, si no hubo **ningún cambio en datos ni en metadatos de una distribución, no debería considerarse actualizada**_
**no actualizados**:   _son las distribuciones con series de tiempo que hay en datasets marcados como **indexables** que no tuvieron **ningún cambio en datos ni en metadatos en esta corrida**_
**error**:  _son las distribuciones cuya actualización se intentó pero arrojaron error parcial o total en el intento de actualización_
**totales**: _es el total de distribuciones con series de tiempo que hay en los catálogos indexables al día de hoy (distribuciones indexables + distribuciones no indexables)

`Series`:
**nuevos**: _son las series de tiempo que la API encontró en datasets nuevos en esta corrida, que no había visto antes. Son las pertenecientes a distribuciones de los datasets que se agregan a la lista de datasets con default "no indexable" por primera vez. Permiten al usuario saber cuántas nuevas series de tiempo hay para su consideración_.
**no indexables**: _la cantidad de series de distribuciones con series de tiempo que hay en datasets marcados como "no indexables", incluyendo los nuevos incorporados en esta corrida_
**indexables**: _la cantidad de series de distribuciones con series de tiempo que hay en datasets marcados como "indexables"_
**actualizados**:  _la cantidad de series de distribuciones con series de tiempo que hay en datasets **indexables** que tuvieron por lo menos alguna modificación de datos o metadatos en la corrida de indexación, si no hubo **ningún cambio en datos ni en metadatos de una distribución, no debería considerarse actualizada**_
**no actualizados**:   _son las series de distribuciones con series de tiempo que hay en datasets marcados como **indexables** que no tuvieron **ningún cambio en datos ni en metadatos en esta corrida**_
**error**:  _son las series cuya actualización se intentó pero arrojaron error parcial o total en el intento de actualización_
**totales**: _es el total de series de distribuciones con series de tiempo que hay en los catálogos indexables al día de hoy (series indexables + series no indexables)

**Comment by abenassi** [comment]
@abenassi tiene que segmentar este issue sacando "Observaciones" para afuera

**Comment by lucaslavandeira** [comment]
@abenassi consulta: La aplicación actualmente no tiene concepto de "dataset erróneo" porque la operación de indexación se hace al nivel de distribución. El campo de datasets "error", entonces, debería indicar la cantidad de datasets que tienen por lo menos una distribución errónea, o simplemente podría ser obviado?

**Comment by abenassi** [comment]
@llavandeira la interpretación 1 es la correcta: "la cantidad de datasets
que tienen por lo menos una distribución errónea"

**Comment by poligarcia** [comment]
Este issue lo vamos a usar para registrar el trabajo de agregar los indicadores de Catálogo (#210), Datasets (#209), Distribución (#208) y Serie (#207) al reporte de indexación.
