### ISSUE TITLE
Acumulación de indicadores del reporte de indexación en una base

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#203]
@lucaslavandeira la idea es nombrar los indicadores siguiendo la misma lógica / patrón de nombre que usamos en `monitoreo-apertura`: fijate por favor en https://docs.google.com/spreadsheets/d/1fNdGKPKHrI2_KhZnRz0j6Hnm804FcsxdZXcI9c2Z2Ws/edit#gid=0 los *indicador_nombre* que le pusimos a cada uno, y usemos el mismo nombre (cuando el indicador es el mismo) y el mismo criterio para nombrar nuevos indicadores por favor.

Además habría que duplicar ese mismo spreadsheet con esa estructura (el que te pegué arriba) y ponerlo en el Drive que tenemos compartido con Devartis para bajar la descripción de los indicadores que acumulamos de Series de Tiempo de la misma manera que hicimos con monitoreo-apertura. Probablemente te sirva hacer ese laburo _antes de implementar en lugar de después_ porque te va a clarificar / chequear lo que efectivamente tiene que recolectar cada indicador.

**Comment by lucaslavandeira** [comment]
La persistencia fue implementada en #206, este issue se interpreta como el agregado de features para mostrar los indicadores de manera equivalente a como lo hace monitoreo-apertura, y la creación de la spreadsheet que lo acompaña.

**Comment by poligarcia** [comment]
Queda pendiente en este issue armar el spreadsheet nuevo para los indicadores de time_series

**Comment by abenassi** [comment]
@poligarcia cerrar este issue y agregar uno nuevo más explícito para el tema de bajar la documentación de los indicadores de reporting de series de tiempo a un spreadsheet en google doc tal como hicimos en monitoreo-apertura

**Comment by lucaslavandeira** [comment]
Se puede ver una primera versión en 
https://docs.google.com/spreadsheets/d/1iWalX1DxyARvuGQyyE-HjVFsWp3N9Ms5THeiCPeBXyc/edit#gid=0
El issue se considerará cerrado luego de por lo menos un ciclo de feedback y correciones
