### ISSUE TITLE
Analizar e incrementar el incremento del límite máximo de series que en una sola call

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#205]
**Contexto**

Los usuarios de la API están pidiendo incrementar el límite de columnas habilitadas para una sola consulta.

La mayoría de las consultas grandes deseadas se ubican entre 35 y 50 columnas, siendo 40 el número más pedido.

Con 20 columnas cubrimos el tamaño del 52% de las distribuciones.
Con 30 columnas cubrimos el tamaño del 68% de las distribuciones (+14%).
Con 40 columnas cubrimos el tamaño del 74% de las distribuciones (+6%).
Con 50 columnas cubrimos el tamaño del 80% de las distribuciones (+6%).

**Propuesta**

Realizar cuatro análisis de performance sobre la instancia de staging para decidir un incremento del límite de columnas a 30, 40 o 50 (el cuarto es el de la situación base con 20).

El análisis podría consistir en levantar el límite de columnas en la instancia de desarrollo y probar en cada caso hacer 1000 queries que soliciten X series aleatoriamente elegidas de la base (c/query debría seleccionar, por ejemplo, 30 series aleatorias de la base para consultar) siendo X = 30, 40 o 50 según la prueba.

El formato del reporte de performance podría ser el mismo que el de la primer prueba de performance en Diciembre, y también nos es de utilidad para chequear si parece haber cambiado la performance en algún aspecto después de 3 meses de desarrollo.

**Comment by abenassi** [comment]
@lucaslavandeira pasamos el límite a 40 series que es el punto donde la performance de queries grandes vs. queries chicas es casi idéntica.

**Comment by lucaslavandeira** [comment]
done
