### ISSUE TITLE
Cálculo de métricas de campos de Series para reporte de indexación

### ISSUE THREAD

**Issue by poligarcia** [datosgobar/series-tiempo-ar-api#207]
**Contexto**

Al reporte de indexación tal como está ahora le faltan varios campos para:

+ Entender mejor el resultado de la corrida (monitoreo API)
+ Seguir la evolución del universo de series disponible en la red de nodos (monitoreo nodos)

`Series`:
**nuevos**: _son las series de tiempo que la API encontró en datasets nuevos en esta corrida, que no había visto antes. Son las pertenecientes a distribuciones de los datasets que se agregan a la lista de datasets con default "no indexable" por primera vez. Permiten al usuario saber cuántas nuevas series de tiempo hay para su consideración_.
**no indexables**: _la cantidad de series de distribuciones con series de tiempo que hay en datasets marcados como "no indexables", incluyendo los nuevos incorporados en esta corrida_
**indexables**: _la cantidad de series de distribuciones con series de tiempo que hay en datasets marcados como "indexables"_
**actualizados**:  _la cantidad de series de distribuciones con series de tiempo que hay en datasets **indexables** que tuvieron por lo menos alguna modificación de datos o metadatos en la corrida de indexación, si no hubo **ningún cambio en datos ni en metadatos de una distribución, no debería considerarse actualizada**_
**no actualizados**:   _son las series de distribuciones con series de tiempo que hay en datasets marcados como **indexables** que no tuvieron **ningún cambio en datos ni en metadatos en esta corrida**_
**error**:  _son las series cuya actualización se intentó pero arrojaron error parcial o total en el intento de actualización_
**totales**: _es el total de series de distribuciones con series de tiempo que hay en los catálogos indexables al día de hoy (series indexables + series no indexables)

Este issue se desprende del original #197

**Comment by abenassi** [comment]
@lucaslavandeira  revisar las definiciones de los indicadores de series y cambiar el comportamiento de la rutina para que no tenga en cuenta las entidades hijos de las entidades padre que son no indexables.

**Comment by abenassi** [comment]
@lucaslavandeira @poligarcia revisar performance
