### ISSUE TITLE
Persiste el error para la descarga de analytics exportados a CSV

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#223]
http://apis-stg.datos.gob.ar/series/analytics/analytics.csv

Este endpoint todavía devuelve "Failed download". Se había arreglado brevemente una vez corriendo algún comando custom en algún lado, pero la solución no quedó impactada / permanente. Habría que dejarlo solucionado.

**Comment by abenassi** [comment]
@lucaslavandeira @poligarcia actualización sobre el estado del error.

**Instancia en producción**

Hoy César hizo un deploy a producción de la `1.0.9-beta` y los analytics se descargan pero hasta cierta fecha (que es la misma de la última vez que los descargué, con lo cual el archivo está ahí y se puede descargar, pero supongo que _no se está generando de nuevo_).

Veo que la cantidad de queries es mayor y hay queries del día de hoy, pero no llegan al CSV.

**Instancia en staging**

Esto sigue igual: exporto a CSV, intento descargar y me tira un "Failed download".

**Comment by lucaslavandeira** [comment]
Beni la generación del archivo es manual, uno tiene que decirle a la
aplicación que regenere el archivo. Esto puede ser modificado a futuro sin
mayores problemas.

2018-03-15 12:23 GMT-03:00 Agustín Benassi <notifications@github.com>:

**Comment by abenassi** [comment]
@lucaslavandeira sí sí, es manual. El día que probé estaba usando el "Export to CSV" y me pasaba eso *de todas maneras*, como si no estuviera funcionando el botón "Export to CSV".

De todas maneras en staging parece funcionar bien... así que veamos si la versión `1.0.10-beta` ya soluciona este tema y el "Failed.."
