### ISSUE TITLE
Crear Jupyter Notebook con tests de integración que usan la API y que va al repositorio

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#249]
**Contexto**

Se necesita alguna herramienta de testeo de integración, que pueda entender / correr alguien de producto, un usuario de la API que lee su documentación y quiere probarla o el equipo de desarrollo.

Para el usuario de la API, es una forma de empezar a probar / usar los features de la API con casos reales y variados, y agilizar su curva de aprendizaje / abordaje de la API.

Para la gente de producto o el equipo de desarrollo, es una forma de controlar (y entender qué cosas se están controlando) que ante un nuevo release / deploy de la API los features funcionan correctamente.

**Propuesta**

La herramienta debe testear el funcionamiento de los endpoints `series` y `search` de la API automatizando lo que haría un usuario que le pegara manualmente al endpoint probando algunas cosas para revisar su funcionamiento. 

Los tests pueden partir de la descarga del CSV de metadatos de las series, que contiene la lista de series disponibles en la base públicamente para el usuario que se la descarga de datos.gob.ar (http://infra.datos.gob.ar/catalog/modernizacion/dataset/1/distribution/1.2/download/series-tiempo-metadatos.csv ).

- [x] Pegarle a todas las series_id que están en el CSV de metadatos de las series. Controla que todas las series publicadas como disponibles para el usuario en datos.gob.ar están efectivamente disponibles en la API.
- [x] Dado el id de alguna serie cualquiera, probar que las funciones de transformación operan correctamente (variación %, variación % interanual, etc).
- [ ] Dadas series de distintas frecuencias y que intersectan en períodos temporales en una misma consulta, probar que las funciones de agregación temporal operan correctamente (como se agrega en meses, trimestres, etc)
- [x] Permitir utilizar los mismos tests con diferentes parámetros adicionales en la API para probar que el resultado es el mismo, como el caracter separador del CSV, etc.

**Comment by abenassi** [comment]
@lalo73 ahí agregué una descripción más bajada del tema. Como apuntamos a que también sea algo útil para un usuario de la API, me parece que Jupyter es la herramienta.

Este issue #249 apunta a ser un testeo _no automático_ que hace conscientemente una persona para probar y ver cómo sale un release (probablemente jugando un poco con las funciones en el Jupyter para ver los últimos datos de alguna serie, o cosas así, que permitan tener un control más directo sobre lo que la API tiene y está mostrando).

Esto no quita que si les parece que suma valor de testeo automático usar alguna herramienta como jmeter para incluir testeos de integración que se corran con cada release, *me parece perfecto que los hagamos en este sprint* pero agreguémoslo como otra tarjeta más.

**Comment by poligarcia** [comment]
Para dar por cerrado este issue queda pendiente:

* [ ] Buscar el lugar adecuado en el repo para el notebook.
* [ ] Parametrizar la URL base de la API.
* [ ] Agregar casos de tests de `min` y `max`.
