### ISSUE TITLE
Refactor a modelos de la API para facilitar el cálculo de indicadores de indexación

### ISSUE THREAD

**Issue by lucaslavandeira** [datosgobar/series-tiempo-ar-api#251]
Refactorizar los modelos de la API (en particular Distribution y Field) de manera que se tengan que hacer menos cálculos en memoria para calcular indicadores. 

En particular, cambiar la lógica de indexación para que  **siempre** inicialice los modelos, y que exista un campo `available` que diga si la entidad se encuentra disponible o no.

**Comment by poligarcia** [comment]
Este issue se va a trackear en datosgobar/django-datajsonar
