### ISSUE TITLE
Series destacadas

### ISSUE THREAD

**Issue by poligarcia** [datosgobar/series-tiempo-ar-api#265]
Como administrador de la API de series de tiempo, quisiera poder definir una o más series de tiempo como "Destacadas".

Una serie destacada es simplemente una marca que recibe un `Field`.

Debe existir un endpoint en la API de búsqueda llamado `/series/api/search/starred` que devuelva los resultados con la siguiente forma:

```
{
  count: 10,
  limit: 10,
  data: [
  {
    title: "ica_exportaciones_animales_vivos",
    id: "75.1_IEAV_0_A_32",
    description: "Exportaciones de animales vivos. En millones de dólares FOB",
    units: "Millones de pesos",
    dataset_publisher_name: "Publisher name",
    dataset_<otros atributos>
  },
  (...)
}
```

Este issue es requerido para datosgobar/series-tiempo-ar-webui#3

**Comment by abenassi** [comment]
@poligarcia habíamos definido que las series destacadas las elige manualmente el usuario de  datosgobar/series-tiempo-ar-webui que es el que va a poner en su página web un buscador de series de tiempo y es el que tiene el criterio para elegir destacar series. Datos.gob.ar _como administrador de la API_ no tiene nada que decir acerca de que series considera destacadas o no.

Datos.gob.ar _como uno de los usuarios de_ datosgobar/series-tiempo-ar-webui sí querrá elegir algunas series para mostrar _en su página web_ como destacadas.

Este issue podría ser re-pensado en la API (pero es para más adelante, no para esta iteración) para ofrecer un endpoint  `/series/api/search/popular` que devuelva las X series más populares en orden de cantidad de consultas a la API en Y período de tiempo.

**Comment by poligarcia** [comment]
ahhh cierto! Lo olvidé por completo! Simplifica muchísimo la implementación!

**Comment by abenassi** [comment]
Este issue pierde vigencia por la implementación del parámetro `sort` en el endpoint `search` que va a permitir pedir las X series más populares según 4 medidas distintas de popularidad.
