### ISSUE TITLE
Implementar dumps en XLSX

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#266]
**Diferencias con el caso de CSV**

El XLSX tienen hasta 1 millón de filas, así que las distribuciones que tienen una fila por observación (son unos 3 millones de valores) deben ser **separadas por frecuencia** usando un diccionario de nombres ad-hoc para traducir la frecuencia desde ISO a un nombre para el usuario (ver ejemplo en datos.gob.ar).

**Comment by lucaslavandeira** [comment]
Cerrado en #376

**Comment by abenassi** [comment]
+ Cuando una frecuencia supera el millón de filas se agrega una hoja con un número extra en el nombre
+ Al separar una frecuencia en hoja aparte, no cortar la serie sino dejarla en una hoja u otra

**Comment by abenassi** [comment]
Sólo falta arreglar la generación de uno de los XLSX
