### ISSUE TITLE
Implementar metadatos enriquecidos necesarios para el explorador de series y el dump

### ISSUE THREAD

**Issue by SebastianHGonzalez** [datosgobar/series-tiempo-ar-api#294]
**Contexto**

Tanto series-tiempo-ar-explorer como la generación del dump requieren el cálculo de metadatos enriquecidos de las series basados en el análisis *de los datos indexados*.

**Propuesta**

Estos metadatos enriquecidos que provienen de cálculos deben agregarse al modelo `Field` y aparecer en los objetos field tanto del endpoint `search` como del objeto `meta` del endpoint `series`.

**Notas**

El orden para agregar un nuevo metadato enriquecido de nivel serie es:

+ Se implementa la lógica de cálculo durante la federación de datos
+ Se guarda el nuevo metadato de nivel serie en la base relacional
+ El metadato debe poder aparecer en el endpoint `series` en el objeto `meta.field` 
+ Agregar el nuevo metadato a la federación de metadatos en elastic search para que aparezca en el endpoint `search`

**Campos a agregar**

Deben tener un nombre en inglés de estilo y lógica similar a los metadatos del perfil de metadatos:

+ 
+
+
+
+

Ahora el enpoint de search retorna algo de la pinta

```
data:  [{
            "field":
                {
                    "id":
                        "364.1_COMERCIALIAL__9",
                    "description": "Comercial"
                    , "title": "comercial"
                },
            "dataset": {
                "title": "Producci\u00f3n y consumo de gas natural",
                "publisher": {
                    "name": "Subsecretar\u00eda de Programaci\u00f3n Macroecon\u00f3mica."
                }
            }
        },
...
```

Falata agregar `field.accuralPeriodisity`, `field.index.start` y `field.index.end`

**Comment by abenassi** [comment]
@abenassi debe completar lista de los nuevos metadatos enriquecidos de nivel serie

**Comment by lucaslavandeira** [comment]
@abenassi tengo anotados:
- serie_inicio
- serie_final
- serie_frecuencia (accrualPeriodicity del indice)
- serie_valores_cant
- series_dias_no_cubiertos
- serie_actualizada (bool)
- serie_valor_ultimo
- serie_valor_anterior
- serie_var_pct_anterior

Con estos creo que es suficiente para cubrir necesidades de explorer + metadata. Faltaría alguno?
