### ISSUE TITLE
Hay series en prod que están federadas pero no se puede acceder por la API, esto no pasa en stg

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#297]
**Contexto** 

Se prueba si están todas las series con `make test-queries num=20 url=`  completando la URL con el base url que corresponda a stg y prod (http://ip_number).

En prod muchas series están "inexistentes" desde la consulta por API.

**Comment by lucaslavandeira** [comment]
Resuelto. Era un problema de infra relacionado a RQ workers, habían algunos mal configurados en la instancia equivocada, que fallaban al intentar leer los archivos fuente de las distribuciones del file system local.
