### ISSUE TITLE
Revisar el funcionamiento y configuración de los repeatable jobs y el mail que llega fuera de hora

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#298]

**Comment by lucaslavandeira** [comment]
Se agregaron instrucciones en el repo de deploy para mitigar el problema

**Comment by abenassi** [comment]
Lucas, estas instrucciones en qué consisten?? Si las tiene que ejecutar el
administrador de datos de la API (no el administrador *de sistemas*)
deberían estar junto con las instrucciones generales de uso/configuración
de la aplicación.
