### ISSUE TITLE
Corregir la UI de admin de AnalyticsImportTask

### ISSUE THREAD

**Issue by lucaslavandeira** [datosgobar/series-tiempo-ar-api#303]
En particular:
- Permitir que funcione el History de los modelos creados manualmente
- Arreglar mensajes de error inconsistentes cuando se usa el botón "Save and add another"

**Comment by abenassi** [comment]
@lucaslavandeira podés revisar este issue para ver si perdió vigencia y lo podemos cerrar?

**Comment by lucaslavandeira** [comment]
Sí, perdió vigencia porque pasamos a usar la funcionalidad de tasks de django_datajsonar. Lo cierro
