### ISSUE TITLE
Federación de observaciones nuevas en series actualizadas

### ISSUE THREAD

**Issue by poligarcia** [datosgobar/series-tiempo-ar-api#315]
Se reportó que series mensuales con observaciones nuevas en el dump no fueron actualizadas en el mismo día en el que aparecieron los datos.

Sí aparecieron los datos al día siguiente.

Es importante encontrar el motivo de la demora en aparecer de estos datos.

**Comment by lucaslavandeira** [comment]
Se agrega un test en #317 para verificar que la rutina de indexación funciona correctamente, pero no se logró reproducir en un ambiente de desarrollo.

**Comment by poligarcia** [comment]
@abenassi te parece esperar a ver qué pasa en la próxima corrida de _datos importantes_, si con el reschedule de las tareas que hiciste se arregla este problema?

**Comment by abenassi** [comment]
@poligarcia los 14 de cada mes se carga el dato de inflación, pero no sé cuándo hay otro dato de alta relevancia antes de eso.. de todas maneras sí, considerémoslo cerrado este issue hasta que que haya otro caso

**Comment by poligarcia** [comment]
Ok!
