### ISSUE TITLE
Nombre del parámetro para paginar en el endpoint de búsqueda

### ISSUE THREAD

**Issue by poligarcia** [datosgobar/series-tiempo-ar-api#318]
El nombre del parámetro de URL usado para paginar en el endpoint de búsqueda de series (`/search`) se llama `offset`.

En el endpoint de datos (`/series`) éste parámetro se llama `start`.

Para mantener compatibilidad con este último endpoint, decidimos renombrar el parámetro `offset` a `start`.

**Comment by abenassi** [comment]
Conservar `offset` como alias, pero el parámetro esperado y documentado es `start`. Ambos deben funcionar.
