### ISSUE TITLE
El parámetro `limit` no funciona bien en combinación con operaciones de transformación

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#340]
http://apis-stg.datos.gob.ar/series/api/series/?ids=103.1_I2N_2016_M_15:percent_change_a_year_ago&limit=5

debería arrojar los primeros 5 valores de variación porcentual interanual que se pueden calcular con una serie que arranca en 2016-04 (esto es, la serie transformada solicitada debería empezar en 2017-04 y llegar hasta 2017-08 inclusive - 5 períodos).

En su lugar, la consulta no arroja ningún valor hasta que el `limit` supera los 12 períodos:

http://apis-stg.datos.gob.ar/series/api/series/?ids=103.1_I2N_2016_M_15:percent_change_a_year_ago&limit=13

**Comment by lucaslavandeira** [comment]
Posible duplicado de #323
