### ISSUE TITLE
`index_start` y `index_end` no cumplen con ISO 8601

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#341]
Deberían ser `YYYY-MM-DDTHH:MM:SS`.

<img width="596" alt="screenshot 2018-08-07 15 03 32" src="https://user-images.githubusercontent.com/4405346/43794177-e12e1526-9a53-11e8-8f76-a2d2220d6860.png">

**Comment by abenassi** [comment]
Vuelvo para atrás porque en staging todavía sigue devolviéndose un string que no cumple con ISO 8601: podría devolver "2016-04-01" o "2016-04-01T00:00:00" pero no "2016-04-01 00:00:00"

![Screenshot 2018-08-14 21.03.04.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5669d6f56378e7130054f97e/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc64167f3e7850e37921cbb37bf1122f43434d0eee1e020a17b8eb8339a3bf6a7082580defd46f0d7cce3511acbed01dea53bb22d95d99a4fedb1294b7607caddecd5d340c041f83fe5836a49b42c95cf44fe24f51b65e.png)

**Comment by lucaslavandeira** [comment]
Corregido con una reindexación de todos los datos
