### ISSUE TITLE
Implementar diccionario donde se asigna a una unidad de medida el atributo de ser porcentual

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#378]
**Contexto**

El desarrollador de front-end necesita saber si una unidad de medida (texto libre especificado por los publicadores) debe ser considerada como porcentual para mostrar en una UI formateando correctamente.

**Propuesta**

Implementar una vista en la UI de Django que liste todas las unidades de medida actualmente indexadas (o que fueron indexadas alguna vez, caso de que se dejen de usar) y permita establecer si son o no unidades porcentuales.

**Comment by lucaslavandeira** [comment]
Trackeado en #478 y #479
