### ISSUE TITLE
Investigar error_msg not null en producción

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#379]
Excepción en distribución 0d1af33c-2791-4114-a276-51fe70478a09: null value in column “error_msg” violates not-null constraint
DETAIL: Failing row contains (1429, 0d1af33c-2791-4114-a276-51fe70478a09, , http://datos.minem.gob.ar/dataset/590d1284-fd6d-4686-afd8-b3da5d..., t, , , null, 306, f, t, Serie histórica de producción de gas natural por cuenca (SESCO..., f, null).

Ocurre con una distribución *nueva* de series de tiempo del catálogo de Energía.

**Comment by lucaslavandeira** [comment]
Solucionado arreglando un problema con los workers surgido en el último deploy
