### ISSUE TITLE
EndDate atrazado

### ISSUE THREAD

**Issue by marianoarga** [datosgobar/series-tiempo-ar-api#382]
El resultado de una consulta con EndDate actual (2018-10-19) no parece ser acorde,  el mismo solo devuelve resultados hasta el 2018-10-11
La documentacion menciona que el servicio es de actualizacion diaria.
https://apis.datos.gob.ar/series/api/series/?ids=168.1_T_CAMBIOR_D_0_0_26&start_date=2018-10-02&end_date=2018-10-19&limit=1000

**Comment by abenassi** [comment]
@marianoarga la API actualiza diariamente (4 veces por día) la base de datos interna contra los datos originales publicados por los organismos, pero esto no implica que los datos en sí mismos se actualicen diariamente. Esto depende de cada organismo y de cada área publicadora, algunas series diarias (por ejemplo) se actualizan con hasta 1 o 2 semanas de demora.
