### ISSUE TITLE
Las hojas generadas en el XLSX después de la "1" no tienen headers en la primer fila

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#411]
Cuando hay una frecuencia que excede el tamaño máximo y genera más de una hoja ("diaria-1", "diaria-2") las que no son la "1" no tienen los headers en la primera fila de la hoja.

Ej.: "diaria-2" en http://apis-stg.datos.gob.ar/series/api/dump/series-tiempo-valores.xlsx

**Comment by lucaslavandeira** [comment]
Cerrado en 9fb6d0277ba4284479786b2274d3392242dd2c60
