### ISSUE TITLE
Cambiar la extensión del dump SQLITE

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#412]
Elegir .db o .sqlite, impactar en el archivo cuando se descomprime y en la URL  "-sqlite" en lugar de "-sql".

**Comment by abenassi** [comment]
@lucaslavandeira esto me parece que no está hecho, o no está en staging

https://apis-stg.datos.gob.ar/series/api/dump/series-tiempo.sqlite
https://apis-stg.datos.gob.ar/series/api/dump/series-tiempo.db

Ninguna funciona

**Comment by lucaslavandeira** [comment]
Están zipeados

> http://apis-stg.datos.gob.ar/series/api/dump/series-tiempo-sqlite.zip/

**Comment by abenassi** [comment]
Ahhhhh oka

**Comment by abenassi** [comment]
Excelente!

**Comment by abenassi** [comment]
@lucaslavandeira necesitamos deshabilitar la anterior: https://apis-stg.datos.gob.ar/series/api/dump/energia/series-tiempo.sql
