### ISSUE TITLE
El mail de reporte indica menos queries "del día anterior" a la mañana que a la tarde

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#416]
En un orden de magnitud de 10 veces menos, aproximadamente.

**Comment by abenassi** [comment]
@lucaslavandeira sumo a este issue parametrizar el horario de corrida de la importación de analytics desde el admin de Django, para que se pueda modificar sin intervención de sysadmn

**Comment by lucaslavandeira** [comment]
Corregido, era un error de configuración en el panel de administración.
