### ISSUE TITLE
Revisar modelos y nombres en el admin de Django

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#424]
**Contexto**

Actualmente resulta difícil administrar la aplicación porque los nombres de las acciones disponibles y agendables quedaron deprecados y asignados en distintos módulos que no tienen un scope claro.

**Propuesta**

+ [ ] Revisar que las acciones disponibles tengan un nombre declarativo de lo que hacen
+ [ ] Revisar que las acciones disponibles estén agrupadas de manera conveniente en módulos / modelos, y los nombres de estos
+ [ ] Revisar que todos los parámetros configurables de la aplicación están disponibles en la UI del admin de Django

**Comment by abenassi** [comment]
@lucaslavandeira vuelvo esto para atrás porque me parece que necesitamos formular la tarea de otra manera. El miércoles necesitaría que te vengas preparado para contarme dentro del admin de Django donde y cómo se configura c/u de las cosas que son configurables en la aplicación.

Dps de eso, yo me llevo el tema y re pienso los nombres de todos los módulos para que digan mejor lo que  hacen. Va a ser más fácil.

**Comment by lucaslavandeira** [comment]
Reformulado en #443 y #444
