### ISSUE TITLE
Comprimir el dump valores del DTA

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#427]
Todas las distribuciones de "valores" deben estar comprimidas, salvo XLSX *que ya es un formato comprimido*.

Anular https://apis-stg.datos.gob.ar/series/api/dump/series-tiempo-valores.dta

Y generar https://apis-stg.datos.gob.ar/series/api/dump/series-tiempo-valores-dta.zip

**Comment by lucaslavandeira** [comment]
Corregido en 37e90453ca3c9cdbfb7edd85064ea1e121cb17d9
