### ISSUE TITLE
Spike: opciones para customizar el look & feel del admin de Django

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#446]
+ Modificar orden de las apps
+ Rename de las apps
+ Shortcuts a acciones muy frecuentes

**Comment by lucaslavandeira** [comment]
> Modificar orden de las apps
https://github.com/mishbahr/django-modeladmin-reorder

> Rename de las apps
Muy fácil desde django mismo, existe un campo `verbose_name` para las aplicaciones

> Shortcuts a acciones muy frecuentes
https://github.com/alesdotio/django-admin-shortcuts
