### ISSUE TITLE
Consulta incorrecta que devuelve status 200

### ISSUE THREAD

**Issue by melikes** [datosgobar/series-tiempo-ar-api#447]
En los csv de los analytics encontramos algunos querystrings incorrectos que devolvieron `status_code = 200`

<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>id</th>      <th>ip_address</th>      <th>host</th>      <th>uri</th>      <th>querystring</th>      <th>start_time</th>      <th>request_time</th>      <th>status_code</th>      <th>api_data</th>      <th>user_agent</th>      <th>token</th>      <th>x_source</th>      <th>request_method</th>      <th>ids</th>    </tr>  </thead>  <tbody>    <tr>      <th>9020</th>      <td>7443841</td>      <td>66.102.8.49</td>      <td>apis.datos.gob.ar</td>      <td>/series/api/series/</td>      <td>ids=162.3_XTALTAL_0_0_7%2C349.2_ACUM_MENSUAL__13%3Bx_residuos_desperdicios_industrias_alimentarias&amp;start_date=2010-12-01&amp;collapse=month&amp;format=csv</td>      <td>2018-09-27 19:22:02+00:00</td>      <td>0.181</td>      <td>200.0</td>      <td>series-tiempo-prod</td>      <td>Mozilla/5.0 (compatible; GoogleDocs; apps-spreadsheets; +http://docs.google.com)</td>      <td>NaN</td>      <td>NaN</td>      <td>NaN</td>      <td>[162.3_XTALTAL_0_0_7, 349.2_ACUM_MENSUAL__13;x_residuos_desperdicios_industrias_alimentarias]</td>    </tr>    <tr>      <th>9078</th>      <td>7443922</td>      <td>66.102.8.51</td>      <td>apis.datos.gob.ar</td>      <td>/series/api/series/</td>      <td>ids=162.3_XTALTAL_0_0_7%2C349.2_ACUM_MENSUAL__13%3B162.3_XSIDUOSIAS_0_0_47%3B162.3_XHICULORES_0_0_33%20&amp;start_date=2010-12-01&amp;collapse=month&amp;format=csv</td>      <td>2018-09-27 19:30:27+00:00</td>      <td>0.185</td>      <td>200.0</td>      <td>series-tiempo-prod</td>      <td>Mozilla/5.0 (compatible; GoogleDocs; apps-spreadsheets; +http://docs.google.com)</td>      <td>NaN</td>      <td>NaN</td>      <td>NaN</td>      <td>[162.3_XTALTAL_0_0_7, 349.2_ACUM_MENSUAL__13;162.3_XSIDUOSIAS_0_0_47;162.3_XHICULORES_0_0_33 ]</td>    </tr>    <tr>      <th>9081</th>      <td>7443927</td>      <td>66.102.8.51</td>      <td>apis.datos.gob.ar</td>      <td>/series/api/series/</td>      <td>ids=162.3_XTALTAL_0_0_7%2C349.2_ACUM_MENSUAL__13%3B162.3_XSIDUOSIAS_0_0_47%3B162.3_XHICULORES_0_0_33&amp;start_date=2010-12-01&amp;collapse=month&amp;format=csv</td>      <td>2018-09-27 19:30:46+00:00</td>      <td>0.178</td>      <td>200.0</td>      <td>series-tiempo-prod</td>      <td>Mozilla/5.0 (compatible; GoogleDocs; apps-spreadsheets; +http://docs.google.com)</td>      <td>NaN</td>      <td>NaN</td>      <td>NaN</td>      <td>[162.3_XTALTAL_0_0_7, 349.2_ACUM_MENSUAL__13;162.3_XSIDUOSIAS_0_0_47;162.3_XHICULORES_0_0_33]</td>    </tr>  </tbody></table>

Probé esta llamada con la primera querystring de la tabla anterior y obtuve error _Serie inexistente_: https://apis.datos.gob.ar/series/api/series/?ids=162.3_XTALTAL_0_0_7%2C349.2_ACUM_MENSUAL__13%3Bx_residuos_desperdicios_industrias_alimentarias&start_date=2010-12-01&collapse=month&format=csv

**Comment by lucaslavandeira** [comment]
@melikes actualmente esa query está devolviendo el status code 400, como debería ser. La causa de estos status code 200 en Septiembre 2018 puede deberse a un bug en la aplicación que fue ya corregido, o bien un error en la forma que se guardan los analytics, o se generan los archivos con los que estás trabajando. En este último caso deberíamos revisar la funcionalidad del lado de [api-gateway](https://github.com/datosgobar/api-gateway).
