### ISSUE TITLE
Los metadatos enriquecidos de popularidad de las series son todos iguales

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#489]

**Comment by abenassi** [comment]
![Screenshot 2019-03-08 15.32.12.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5669d6f56378e7130054f97e/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cd6416743e795ce37a25cbb07af1132943434d0eee1e020a17b8eb8339a3bf6a7082580defd46f0d7cce3511acbed01dea53bb22d95d99a4fedb1294b7607caddecd5d340c041f83fe5830a2994cc858f748e14a5db65e.png)

**Comment by lucaslavandeira** [comment]
Faltaba correr un paso manual de inicialización! Corregido
