### ISSUE TITLE
Spike: Modificar la función de ranking de la búsqueda de series usando "popularidad"

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#494]
**Contexto**

De entrevistas con usuarios surgió que los ayudaría a elegir la serie correcta, que aparezcan con más probabilidad las más populares (ie.: generalmente dentro de las cientos de series de inflación disponibles, la más popular es la que suelo querer elegir).

**Propuesta**

Incorporar a la función de ranking de elastic search, el metadato hits_90_days como ponderador adicional donde "más hits" es una serie "mejor rankeada".

Antes de implementar este issue, hacer una propuesta y explicación sobre cómo se incorpora este criterio y con cuánto peso en el ranking final.

**Comment by lucaslavandeira** [comment]
Se puede ponderar de manera muy flexible y configurable un parámetro numérico utilizando "Function Score Queries" de elasticsearch, en particular el tipo de funciones "Field Value factor" nos permite darle un boost de score a queries según un valor numérico de nuestros documentos, especificando un factor de boosting, y una función a aplicarle a los números si no queremos que sea lineal (por ejemplo, aplicar una raíz, o un logaritmo). Dejo un script de ejemplo para generar queries a partir de un parámetro buscado (querystring):
```
import json

function_score = {
    "query": {
        "function_score": {
            "boost_mode": "sum",
            "query": {},
            "boost": "5",
            "field_value_factor": {
                "field": "hits",
                "factor": 1.2,
                "modifier": "log",
                "missing": 1,
            }
        }
    },
    "size": 100,
}

old = {
    "query": {},
    "size": 100
}

querystring = 'ipc'
query = {'query': {'dis_max': {
    'queries': [{'bool': {'should': [{'match': {'dataset_description': querystring}}], 'boost': 1}},
                {'bool': {'should': [{'match': {'dataset_source': querystring}}], 'boost': 1}},
                {'bool': {'should': [{'match': {'dataset_title': querystring}}], 'boost': 1}},
                {'bool': {'should': [{'match': {'description': querystring}}], 'boost': 1.5}}]}}}

function_score['query']['function_score'].update(query)
old.update(query)
print(json.dumps(function_score))
print(' ')
print(json.dumps(old))
```
