### ISSUE TITLE
Missing id-series values

### ISSUE THREAD

**Issue by jdemonasterio** [datosgobar/series-tiempo-ar-api#520]
Are missing-values related issues ok to report in this project? Can gladly close this if necessary :)

According to official docs and to L4294 in [the series list csv](http://infra.datos.gob.ar/catalog/modernizacion/dataset/1/distribution/1.2/download/series-tiempo-metadatos.csv)  a valid  dollar exchange rate series would be: `168.1_T_CAMBIOR_D_0_0_26`. Yet using the following script we see that:

```##  BNA arg dolar  series-id 168.1_T_CAMBIOR_D_0_0_26
import pandas as pd
import requests
import urllib.parse

def get_api_call(ids, **kwargs):
    API_BASE_URL = "https://apis.datos.gob.ar/series/api/"
    kwargs["ids"] = ",".join(ids)
    return "{}{}?{}".format(API_BASE_URL, "series", urllib.parse.urlencode(kwargs))

ds = pd.to_datetime("2018-03-12")

df = pd.read_csv(get_api_call(
    ["168.1_T_CAMBIOR_D_0_0_26"],
    format="csv", start_date=f'{ds:%Y%m%d}'
))
print(df.sort_values(by='indice_tiempo').tail())
```

returns missing dates, namely the last ~9 months.

```python
indice_tiempo  tipo_cambio_bna_vendedor
95    2018-06-15                      28.8
96    2018-06-16                      28.8
97    2018-06-17                      28.8
98    2018-06-18                      28.5
99    2018-06-19                      28.2
```

It would be great to have this serie's  values as the api rocks!

**Comment by lucaslavandeira** [comment]
Thanks for the kind words! The API by default returns the first 100 values of the queried time series. You can increase this limit with the `limit` parameter. Alternatively you can query the last `n` values with the parameter `last=n` (mutually exclusive with `limit`). 

Suffice to say the USD/ARS exchange rate is a very demanded time series and we're always keeping a close eye to have it updated as soon as possible :wink:

**Comment by jdemonasterio** [comment]
Great! Sorry for that. 
Seems to be another PEBKAC case :sweat_smile: . 

Pd: 
IIUC 15 dollar/peso rate days have gone missing under the close watch ;)
```python
import pandas as pd
pd.read_csv(
    'https://apis.datos.gob.ar/series/api/series?start_date=2019-03-28&end_date=2019-04-12&ids=168.1_T_CAMBIOR_D_0_0_26&format=csv&collapse=day')
```
