### ISSUE TITLE
Serie de tipo de cambio inexistente

### ISSUE THREAD

**Issue by fedemoglia** [datosgobar/series-tiempo-ar-api#530]
La serie de tipo de cambio (168.1_T_CAMBIOR_D_0_0_26) no está funcionando. Ninguno de los 3 links que están en https://datosgobar.github.io/series-tiempo-ar-api/ andan. Sin embargo las otras series si muestran datos.
![image](https://user-images.githubusercontent.com/13092392/56700276-d3d92e80-66cf-11e9-8933-ffd2e77f2e27.png)

**Comment by lucaslavandeira** [comment]
Gracias por la notificación. Ya está corregido!
