### ISSUE TITLE
Spike: revisar opciones para marcar distribuciones que son pesadas y requieren timeouts específicos

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#544]
+ timeout específico para una distribución

**Comment by lucaslavandeira** [comment]
La opción de setear un timeout específico es muy viable. 
Pero se investigó un poco la performance de la rutina de indexación e identificamos algunas mejoras de performance, para agilizar el proceso y no requerir aumentar timeouts. Si persisten problemas se puede implementar la opción configurable.
