### ISSUE TITLE
La consulta rompe al especificar un collapse_aggregation sin especificar un collapse

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#559]
esta consulta es exitosa:

https://apis.datos.gob.ar/series/api/series/?ids=148.3_INIVELNAL_DICI_M_26

esta consulta falla:

https://apis.datos.gob.ar/series/api/series/?ids=148.3_INIVELNAL_DICI_M_26&collapse_aggregation=sum

esta consulta no falla:

https://apis.datos.gob.ar/series/api/series/?ids=148.3_INIVELNAL_DICI_M_26&collapse=quarter&collapse_aggregation=sum

Especificar un método de agregación temporal distinto del default (incluso cuando no se esté pidiendo hacer ninguna agregación temporal) no debe romper la consulta.

En el caso de una sola serie es redundante especificarlo (la consulta devuelve lo mismo en cualquier caso). En el caso de múltiples series de frecuencias distintas, siempre se está haciendo una agregación temporal aunque no se especifique el parámetro "collapse", entonces es pertinente especificar "collapse_aggregation" incluso en ese caso.

**Comment by abenassi** [comment]
Revisar que el issue tira un 500: https://apis-stg.datos.gob.ar/series/api/series/?ids=148.3_INIVELNAL_DICI_M_26&collapse_aggregation=sum

**Comment by lucaslavandeira** [comment]
Corregido!
