### ISSUE TITLE
No se puede modificar un syncronizer sin cambiar el nombre

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#571]
<img width="542" alt="Screenshot 2019-06-14 10 01 26" src="https://user-images.githubusercontent.com/4405346/59510989-7ff6f480-8e8b-11e9-85cf-9f5a3e8f604c.png">

**Comment by lucaslavandeira** [comment]
Cerrado a través de datosgobar/django-datajsonar#118
