### ISSUE TITLE
Agregar documentación del endpoint "dump"

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#572]
<img width="1129" alt="Screenshot 2019-06-14 10 28 43" src="https://user-images.githubusercontent.com/4405346/59512504-3dcfb200-8e8f-11e9-9a07-22e8bb5fa999.png">

**Comment by danielaagarcia** [comment]
@lucaslavandeira podrías indicar donde quedó esta documentación?
