### ISSUE TITLE
Spike: pensar cómo abordar el problema de números con pérdida de precisión decimal

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#630]

**Comment by lucaslavandeira** [comment]
Una heurística aceptable termina siendo un redondeo forzado a `16 - digitos_enteros` decimales. 

Se detectaron 300 series con mayor representación decimal que 20. La mitad de ellas son de `bcra`, cuyos datos en la fuente original de scraping (archivos .txt) sólo tienen hasta 11 cifras significativas, es decir, los dígitos adicionales fueron impuestos por un bug de redondeo en el scraper. La otra mitad fueron de `sspm`, y analizando tres fuentes de scraping manualmente (archivos .xlsx) se observó que la cantidad de cifras significativas de algunos datos eran 14.
