### ISSUE TITLE
No hay forma de distinguir explícitamente entre distintas columnas cuando éstas se componen de variantes transformadas de una misma serie

### ISSUE THREAD

**Issue by capitantoto** [datosgobar/series-tiempo-ar-api#64]
### Problema
Los títulos de las series que se le devuelven al consumidor de la API son idénticos para todas las columnas que tengan origen en una misma serie, aunque lleven distintas transformaciones.

Implícitamente, el orden de las columnas es el mismo que el orden en que se declaran los IDs en el request, pero esto peude resultar insuficiente si uno recibe el archivo de un tercero sin tener acceso al request original, o si tiene acceso al request pero se han solicitado muchas transformaciones de una misma serie.

#### Request original
http://181.209.63.223:8095/series/?ids=10.1_ISOA_1993_A_27,10.1_ISOA_1993_A_27:change&format=csv

**Comment by lucaslavandeira** [comment]
Sugerencias para esto? @abenassi @capitantoto 
Me imagino que una solución sería agregar la transformación aplicada (de haberla), por ejemplo para el request dado:
`indice_serie_original_anual,indice_serie_original_anual_change`
o bien idéntico al parámetro `ids`, usando `:`
`indice_serie_original_anual,indice_serie_original_anual:change`

**Comment by abenassi** [comment]
@lucaslavandeira habría que pensar unas cuantas cosas para las variantes de esto, porque los nombres de los campos respetan una serie de restricciones que tendríamos que preservar al appendearle la transformación (al menos cuando el usuario deja el default `names` / `titles` como nombre de campo). De todas maneras este issue está bastante más bajo en prioridad, hay unos cuantos que abordar antes.

**Comment by abenassi** [comment]
Incluso si vemos que no estamos llegando para la fecha de los releases, es posible que esto lo pateemos para versiones posteriores a la *1.0*
