### ISSUE TITLE
Chequear fallas en el test de integración que viene en staging

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#641]

**Comment by lucaslavandeira** [comment]
Se detectaron dos cuestiones:
1. La tarea del test de integración estaba timeouteando. Al ser configurable desde UI, simplemente se subió el tiempo (actualmente tarda ~20 minutos)
2. Discrepancias de tiempo entre la lectura de nodos (hecha a las 12 AM) y el test de integración (hecha como último paso del synchronizer, usualmente varias horas después) dan lugar a que los datos cambien entre ambas ejecuciones, llevando a las discrepancias que vemos en los reportes. Esto se puede confirmar notando que el scraper de series de tiempo corre todas las horas (crontab `0 * * * *`), es muy posible que algún dato se vea modificado entre la lectura y el test de integración.
