### ISSUE TITLE
Las operaciones para modos de representación alternativos deberían suceder después del colapso de la frecuencia temporal

### ISSUE THREAD

**Issue by capitantoto** [datosgobar/series-tiempo-ar-api#67]
### Problema

Actualmente, cuando se solicita una serie colapsada a una frecuencia menor de la original, y a la vez se pide una transformación, el orden de ejecución de las operaciones es:
1) Transformar los valores según se indique con `representation_mode`, y
2) Calcular el valor colapsado según el valor que tome el parámetro `collapse_aggregation` (que según #65, sólo está funcionando como `average`).

...cuando el orden correcto debería ser:

1) Calcular el valor colapsado según el valor que tome el parámetro `collapse_aggregation` (que según #65, sólo está funcionando como `average`), y
2) Transformar los valores según se indique con `representation_mode`.

En un ejemplo trivial, veamos una serie originalmente trimestral
```
gonzalo@negotium:series-tiempo:$curl "http://181.209.63.223:8095/series/?ids=10.2_ISD_1993_T_31&format=csv&limit=9"
indice_tiempo,indice_serie_desestacionalizada
1993-01-01,96.8242984522
1993-04-01,99.56159059059999
1993-07-01,101.468017469
1993-10-01,102.14609348799999
1994-01-01,104.01513912799999
1994-04-01,105.90686034299999
1994-07-01,105.89095643200001
1994-10-01,107.531847205
1995-01-01,105.714380529
```
La misma serie colapsada a años, devuelve correctamente el promedio para la serie sin transformaciones, pero devuelve el promedio de las variaciones (en lugar de la variacion entre los promedios): 
```
gonzalo@negotium:series-tiempo:$curl "http://181.209.63.223:8095/series/?ids=10.2_ISD_1993_T_31,10.2_ISD_1993_T_31:change&format=csv&collapse=year&limit=3"
indice_tiempo,indice_serie_desestacionalizada,indice_serie_desestacionalizada
1993-01-01,100.00000002499999,1.7739316666666667
1994-01-01,105.83620075,1.346438425
1995-01-01,102.82493864999999,-1.294094375
```

Al realizar las transformaciones en este orden, no sólo los valores de la serie en cambios no son los esperados, sino que se reporta un valor para el período inicial, que en realidad debería estar vacío.

### Detalles
Este bug se encontró comparando los resultados de dos consultas:
http://181.209.63.223:8095/series/?ids=10.3_ISD_1993_M_31,10.3_ISD_1993_M_31:change&format=csv&collapse=year
http://181.209.63.223:8095/series/?ids=10.3_ISD_1993_M_31,10.3_ISD_1993_M_31:change&format=csv

Sin embargo, su explicación es más clara con ejemplos pequeños.

**Comment by abenassi** [comment]
Ok Lucas, queda pendiente el tema para mejorar la performance más adelante
entonces. Vamos a tener que ver bien como nos impacta esto cuando hagamos
los tests de carga.
