### ISSUE TITLE
`percent_change_a_year_ago` en `representation_mode` no funciona bien

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#93]
http://181.209.63.223:8095/series/?ids=10.3_ISD_1993_M_31,10.3_ISD_1993_M_31:percent_change&format=csv

No logré darme cuenta qué calculo estará haciendo, pero no es el esperado (en columna D).

<img width="770" alt="screenshot 2017-11-24 18 51 20" src="https://user-images.githubusercontent.com/4405346/33224547-4da46c70-d149-11e7-9053-8b87067ca282.png">

**Comment by lucaslavandeira** [comment]
Esto era un bug de versiones anteriores, que fue arreglado reindexando los datos
