### ISSUE TITLE
Implementar estructura de URLs para las APIs dev y stg

### ISSUE THREAD

**Issue by abenassi** [datosgobar/series-tiempo-ar-api#96]
Este issue depende de algunas acciones por parte de equipo de Datos y otras de Devartis.

**URL de la API staging:**

http://www.apis-stg.datos.gob.ar/series/api/v1.0/series?ids=138.1_PAPDE_0_M_41&format=csv&start_date=2016-01-01&end_date=2016-12-01

**URL de la API dev:**

http://www.apis-dev.datos.gob.ar/series/api/v1.0/series?ids=138.1_PAPDE_0_M_41&format=csv&start_date=2016-01-01&end_date=2016-12-01

**Comment by abenassi** [comment]
@poligarcia estaría ok también que la URL fuera */series/api/series?* en lugar de */series/api/v1.0/series?* para este release, porque de todas maneras es una estructura que mantendríamos como:

1. */series/api/series?* apunta siempre a la última versión estable deployada en producción
2. */series/api/v1.0/series?* apunta a una versión estable _específica_

Tal vez lo mejor ahora es quedarnos sólo con la implementación 1 para no hacernos lío pensando en cómo gestionar el versionado de la API funcionando en Django (deberían convivir varias interfaces, etc.) que creo que es para tratar más adelante con cuidado.

Pero al menos la versión 1 la necesitamos para este release.

cc @pilimayora por si tiene alguna otra opinión

**Comment by pgarcia-uv** [comment]
Con Kong es relativamente sencillo actualizar la parte de `/v<version>`. El tema es si vale la pena hacerlo, considerando que no vamos a manterner (o al menos no lo charlamos) varias versiones en paralelo...

Quizás podemos empezar con la opción 1, y cuando definamos si queremos tener distintas versiones de APIs en paralelo retomamos la versión 2...

**Comment by poligarcia** [comment]
Con Kong es relativamente sencillo actualizar la parte de `/v<version>`. El tema es si vale la pena hacerlo, considerando que no vamos a manterner (o al menos no lo charlamos) varias versiones en paralelo...

Quizás podemos empezar con la opción 1, y cuando definamos si queremos tener distintas versiones de APIs en paralelo retomamos la versión 2...

**Comment by abenassi** [comment]
Dale sí, me parece bien.

En principio el decreto de Modernización Administrativa pide que las APIs
de gobierno mantengan la última versión + la versión anterior. Apuntaríamos
a cumplir con eso, pero definitivamente es una conversación para encarar
más adelante. Hoy no nos importa esto, salvo para no meter la gamba en la
estructura de la URL.

Vamos con 1 entonces, que en cualquier caso la vamos a usar.

**Comment by abenassi** [comment]
@poligarcia @pilimayora cierro este issue por ahora para dejar la discusión de versionado de la aplicación para más adelante
